#+TITLE:  Draft mail 
#+AUTHOR: VLEAD
#+DATE: [2017-03-06  Monday]
#+PROPERTY: results output
#+PROPERTY: exports code
#+SETUPFILE: ./org-templates/level-0.org
#+options: ^:nil


	Greetings from Virtual Labs, IIIT Hyderabad !

	 Virtual Labs is an MHRD Initiative which aims at making available
	 experiments done in Engineering Colleges in a Virtual form, to all
	 the college students as a adjunct facility to the physical
	 labs.These labs provide an opportunity to the students to perform
	 these simulated experiments, read the theory and improve their
	 understanding of the subject.

	 The [[http://www.vlabs.ac.in/][Virtual Labs]] portal provides free access to over 1500
	 experiments in over 9 domains of engineering and science
	 subjects. These can be used anywhere, anytime and on any subject.

	 These experiments are built by 12 leading institutes such as the 6
	 IITs, IIIT Hyderabad, College of Engineering Pune and so on. Thus,
	 the content is best in class.

	 We request <place holder for college name> college, to give us
	 time between <place holder for start time> and <place holder for
	 end time> on <place holder for date and day > to conduct a
	 workshop to familiarize the students and faculty in the use of the
	 Virtual labs- both the internet based version and the College
	 cloud version. [[http://vlabs.ac.in:5959/college-cloud-edition/][College Cloud edition]] is an Internet independent
	 option. The prerequisites that must be made available, for this
	 workshop are detailed in the above page.  The College Cloud
	 version is a newer development and we will run this in the
	 Workshop. Kindly return the [[https://docs.google.com/a/vlabs.ac.in/forms/d/e/1FAIpQLScvUGaE6ln6JzeIVc2CqTXwac_R69WhzoM5TrW6y99hFB6nbw/viewform?embedded=true'][Expression of Interest' document]] duly
	 filled in to us immediately.  We request your confirmation of
	 suitability of doing the workshop and the date and time.

	 We look forward to meeting you and working with you on the Virtual
	 labs
